# Generated by Django 4.2.3 on 2023-07-25 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note_api',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('amount', models.CharField(max_length=100)),
                ('quantity', models.CharField(max_length=100)),
                ('iscompleted', models.BooleanField(default=False)),
            ],
        ),
    ]
